global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "scraper"
    static_configs:
      - targets: ["scraper:8000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
