"""Add price_text to listings

Revision ID: 052cc389a82e
Revises: 80558b78e573
Create Date: 2025-02-17 16:27:01.228823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052cc389a82e'
down_revision: Union[str, None] = '80558b78e573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('price_text', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'price_text')
    # ### end Alembic commands ###
