"""Add unique constraints to listings

Revision ID: 67ffd44bb76c
Revises: a77864259db9
Create Date: 2025-02-05 14:09:52.574923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ffd44bb76c'
down_revision: Union[str, None] = 'a77864259db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_source_external_id', 'listings', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_source_external_id', 'listings', type_='unique')
    # ### end Alembic commands ###
